# Generated by Django 3.0.2 on 2020-05-24 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Patient', '0005_auto_20200525_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutstandingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('outstanding', models.DecimalField(decimal_places=2, max_digits=10)),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.PatientModel')),
            ],
        ),
    ]
