# Generated by Django 3.0.2 on 2020-05-24 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Patient', '0004_auto_20200524_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=6)),
                ('age', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=25)),
                ('attendence', models.IntegerField(default=0)),
                ('sallary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.UserModel')),
            ],
        ),
    ]
