# Generated by Django 3.0.2 on 2020-05-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0003_patientmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmodel',
            name='outstanding',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='paid',
            field=models.IntegerField(default=0),
        ),
    ]
