# Generated by Django 3.0.2 on 2020-05-24 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0004_auto_20200524_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientmodel',
            name='outstanding',
        ),
        migrations.RemoveField(
            model_name='patientmodel',
            name='paid',
        ),
    ]
