# Generated by Django 3.0.2 on 2020-05-24 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0004_auto_20200524_1545'),
        ('doctor', '0002_prescription'),
        ('Receptionist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentsmodel',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.DoctorModel'),
        ),
        migrations.AlterField(
            model_name='appointmentsmodel',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.PatientModel'),
        ),
    ]
