# Generated by Django 3.0.2 on 2020-05-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0002_auto_20200525_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentsmodel',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=10),
        ),
    ]
